export const PUSH_ROUTE = 'PUSH_ROUTE';
export const POP_ROUTE = 'POP_ROUTE';

export const GEOCODE_PENDING = 'GEOCODE_PENDING';
export const GEOCODE_FULFILLED = 'GEOCODE_FULFILLED';
export const GEOCODE_REJECTED = 'GEOCODE_REJECTED';

export const VIEW_LOCATION = 'VIEW_LOCATION';

export const GEOLOCATED = 'GEOLOCATED';
export const TOGGLE_GEOLOCATION = 'TOGGLE_GEOLOCATION';